### ISSUE TITLE
Tactics Pane errors/freezes with alternative preferred threat frameworks

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#1122]
Observed behavior
- With MITRE ATT&CK Enterprise and NTCTF data, those frameworks work as expected
- If a framework is completely unpopulated, it will error out like so:

![image](https://user-images.githubusercontent.com/30236110/41114441-738ba8e8-6a52-11e8-8316-09e1d1be609c.png)

- If a framework has very few (in my case, 1) attack pattern(s), it will freeze the browser tab

To test this case, I created an attack pattern with a MITRE mobile ATT&CK phase and changed my preferred cyber threat framework to MITRE mobile ATT&CK.  This caused a hard freeze on chrome, and I had to go to Apple icon => force quit

**Comment by webiator** [comment]
Left out of the above, when talking about unpopulated frameworks:
1. The framework is populated with phases, but,
2. The phases have no attack patterns listed, so
3. The heatmap displays all the phases in the header part, but they are all scrunched together in the upper left.

With just one attack pattern, the script appears to be stuck calculating widths for all the phases, because, with just one pattern present, the other phases keep throwing NaNs for their widths, which keeps the loop trying to adjust them going on and on and on...

**Comment by webiator** [comment]
Also, the tactics treemap will be blank. It is better for it to at least display the phases, even without any attack pattern data.
