### ISSUE TITLE
Breakdown of assessment by target OS

### ISSUE THREAD

**Issue by underneith** [unfetter-discover/unfetter#531]
Is there any way to reflect maturity of coverage or exposure of attack by operating system type (e.g. Windows, Mac, Linux)?

**Comment by infosec-alchemist** [comment]
Not directly. But you could do it indirectly.  

If a particular attack technique works across multiple platforms, you could create a separate attack pattern for each of those platforms.  That can get a bit messy.  

We hadn't considered rating via a platform because we technically let you rate by Sensor, Mitigation, or Indicator.  not directly the MITRE attack technique.  Likely, your sensor, mitigation or indicator would either work across platforms or is specific to a particular platform.   

If you have a thought about how you would like to see this, please let us know and we can add it to the design discussions.
