### ISSUE TITLE
Ability to visualize analytics in the hub against the ATT&CK matrix

### ISSUE THREAD

**Issue by johnwunder** [unfetter-discover/unfetter#753]
The ATT&CK matrix and heatmaps on top of the matrix are a very common visual element when working with ATT&CK data. Unfetter should let you visualize analytics on the hub in the matrix.

This was reiterated by a few people at the NH-ISAC Analytics WG meeting.

**Comment by dmoore44** [comment]
I've made note of it too: #666

**Comment by infosec-alchemist** [comment]
- [ ] Build mockups of showing a subset of attack techniques displayed with mapped data
- [ ] Determine what subset that is (5 columns?  Pre-attack vs enterprise?)
- [ ] Look at ways to filter, shorten, order the techniques to show the necessary data.
- [ ] Investigate ways to use zooming

**Comment by mushinlogit** [comment]
related to unfetter-discover/unfetter#910
related to unfetter-discover/unfetter#801

**Comment by webiator** [comment]
Is there another visual element needed here to help improve the UI? Here are the features currently available:

- Should the heatmap be a part of the page, rather than an overlay as it currently exists?

- Since it _is_ an overlay, the list of current analytics is also displayed below the heatmap. If you click
on a cell in the heatmap, the cell is colored more darkly, and the list of analytics is changed to show only the analytics that target the attack pattern listed in the cell. This is union, rather than an intersection, filter; clicking on multiple cells lists all the targeting analytics, not the analytics that target all the selected attack patterns.

- The filter (expansion panel on lefthand side) can be used to limit which analytics are displayed. After using the filter panel to reduce the analytics listed, clicking the heatmap overlay reflects the filtered analytics (with no way to edit that filter).

- Note that if we embed the heatmap within the page, we potentially have two physically-separated components that can act as filters on the list of analytics. This is discouraged, since it's confusing to a user, and can make their head spin trying to figure out which filter is affecting them. Another option was to put the heatmap in the filter panel, but it would be so shrunken that it would be really hard to guess which attack pattern you are clicking on.

**Comment by webiator** [comment]
@infosec-alchemist, unless you note otherwise, I think this issue can be closed? Let me know if you think the analytic exchange should have some other visualization for the attack patterns, or if you can see areas for improvement.

**Comment by infosec-alchemist** [comment]
We need to add the kill chain to the map so that there is a better orientation for the user.

We have different options for displaying the heat map in different ways for the threat dashboards.  could we use the same control here?
